### ISSUE TITLE
Provide Windows binary

### ISSUE THREAD

**Issue by simonkrauter** [dom96/Aporia#143]
It would be nice to have a download option for an Aporia binary for Windows.
The readme points to the Nim installer, which does not contain Aporia any more.

**Comment by Alan-FGR** [comment]
Yep.
>The easiest way to install Aporia on Windows is to use one of the Nim windows installers available at the following URL: http://nim-lang.org/download.html#binaries
*clicks link*... *finds no installer whatsoever* :trollface:

**Comment by shevegen** [comment]
Have you guys tried out win10 yet?

It has a *nix subsystem as I call it; presently defaulting to ubuntu but the microsoft team for that subsystem said that they work on fedora, opensuse etc...

I tried it and I can compile pretty much everything there. It's really almost like linux. A few progams behave a bit differently or not at all; lspci for example.

You can actually start xorg programs if you use the
export DISPLAY=:0
trick and have something such as "xmin / ming" available which allows xorg apps to run on windows.

It does not work perfectly; kde konsole does not allow for any input. But gvim and bluefish work perfectly well.

I may give it a try to compile nim and then aporia and see if it works. While this is admittedly not the same as you want (a windows binary e. g. an .exe that can be clicked in order to install aporia), this may work for the time being for those who use win10 for example.

**Comment by dom96** [comment]
@Alan-FGR Fixed :)

Sadly I don't have time to build Aporia binaries, if anyone wants to do that I'll happily link them.

**Comment by Alan-FGR** [comment]
@dom96 :P I wasn't being serious.

Is this project still going strong though?

I feel one of the pain points in adopting nimrod is exactly the lack of tools, or at least clarity regarding the support of the current tools. When you take a look at the "Editor Support" wiki page it lists 20 editors with varying levels of support, some only have syntax highlight, others have autocompletion, linting and debugging, but it's not very clear for example what is the most fully featured. Look how clear that is in https://areweideyet.com/ which shows a feature matrix where you can easily compare that, and also hides the less features editors by default.

That being said, I think nimrod is on the right track by providing official suggestions so development is centralized and the IDEs use that as a back-end. That should be done for all (intelligent) features imho, for example refactoring.

**Comment by dom96** [comment]
> Is this project still going strong though?

It isn't. I've come to the conclusion that GTK is a dead-end and no longer have the time to further develop Aporia unfortunately.

> When you take a look at the "Editor Support" wiki page it lists 20 editors with varying levels of support, some only have syntax highlight, others have autocompletion, linting and debugging, but it's not very clear for example what is the most fully featured. Look how clear that is in https://areweideyet.com/ which shows a feature matrix where you can easily compare that, and also hides the less features editors by default.

You know what all wikis share? They are editable by everyone :)

Please improve our wiki, or better yet create an areweideyet.com equivalent for Nim. These things aren't created by the core devs but by the community, i.e. yourself. I am willing to help you any way I can, just ask.

Btw, it's not called Nimrod anymore. It's Nim.

**Comment by Alan-FGR** [comment]
I guess at the moment the most fully featured editor would be VSCode, but I could be wrong.
In any case I'd love to have the time and resources to create an areweideyet.com equivalent for Nim, I don't have such a privilege though and my to-do list for 'community' stuff is filled with contributions to Atomic, which I hardly have any time for and are of much higher priority to me since it affects me professionally. That being said I have an interest in Nim and I'm adding that to my to-do list, I think it's not strictly necessary to install all the solutions to 'rate' them; that information can be gathered from the community itself, and even the developers I guess would be happy to help.
I can't promise anything though, sorry.
> Btw, it's not called Nimrod anymore. It's Nim.

:trollface:
